name: CI

on:
  pull_request:
  push:
    branches: [$default-branch]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  ci:
    uses: bamr87/.github/.github/workflows/ci.yml@main
    permissions:
      contents: read
      security-events: write
      actions: read
    secrets: inherit
